version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/sales_analytics.db
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./data:/app/data
