"""create calls and analytics tables

Revision ID: 202307280001
Revises: None
Create Date: 2023-07-28

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '202307280001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('agent_talk_ratio', sa.Float(), nullable=True),
    sa.Column('customer_sentiment_score', sa.Float(), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index(op.f('ix_calls_agent_id'), 'calls', ['agent_id'], unique=False)
    op.create_index(op.f('ix_calls_start_time'), 'calls', ['start_time'], unique=False)
    op.create_index('ix_calls_transcript_fts', 'calls', [sa.text("to_tsvector('english', transcript)")], postgresql_using='gin')
    op.create_table('analytics',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('avg_talk_ratio', sa.Float(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics')
    op.drop_index('ix_calls_transcript_fts', table_name='calls')
    op.drop_index(op.f('ix_calls_start_time'), table_name='calls')
    op.drop_index(op.f('ix_calls_agent_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
